#!/bin/bash

# MIT License

# Copyright (c) 2020 Wendy Liga

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

convert_mov_to_gif() {
  mov_source="$1"
  gif_path="$2"
  
  if [ -z "$mov_source" ]; then
    echo "💥 Please enter .mov file Source"
  elif [ -z "$gif_path" ]; then
    echo "💥 Please enter gif file Source"
  else
    echo ""
    echo "🔧 Creating GIF..."
    palette="/tmp/palette.png"

    filters="fps=15,scale=320:-1:flags=lanczos"
    ffmpeg -v warning -i $mov_source -vf "$filters,palettegen=stats_mode=diff" -y $palette
    ffmpeg -i $mov_source -i $palette -loglevel panic -lavfi "$filters,paletteuse=dither=bayer:bayer_scale=5:diff_mode=rectangle" -y $gif_path &> /dev/null

    echo "✅ Grab your GIF at $2"
    # clear source
    rm -f $mov_source
  fi
}

if ! homebrew_loc="$(type -p "brew")" || [[ -z $homebrew_loc ]]; then
    echo "Missing Homebrew, please install Homebrew, for more visit https://brew.sh"
fi

if ! ffmpeg_loc="$(type -p "ffmpeg")" || [[ -z $ffmpeg_loc ]]; then
    echo "💥 Missing ffmpeg, installing...(This may take a while)"
    brew install ffmpeg >/dev/null
fi

echo "⚙️ Recording Simulator... (Press control(^) + c to stop recording.)"
xcrun simctl io booted recordVideo -f ~/video.mov &> /dev/null && convert_mov_to_gif ~/video.mov ~/video.gif