
name: Mimiq CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - '*'
      
jobs:
  macos_test:
    name: MacOS Unit Test
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: swift build
    - name: Build
      run: swift test