
name: Mimiq CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - '*'
      
jobs:
  macos_test:
    name: MacOS Unit Test
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: make test
  ubuntu_xenial_test:
    name: Ubuntu-16.04 Unit Test
    runs-on: ubuntu-16.04
    container: 
      image: vapor/swift:5.2-xenial
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Testing
      run: make test
  ubuntu_bionic_test:
    name: Ubuntu-18.04 Unit Test
    container: 
      image: vapor/swift:5.2-bionic
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Testing
      run: make test