
name: Release

on:
  push:
    tags:
      - '*'

jobs:
  upload_binary:
    name: Upload Binary & Update Homebrew Formula
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compress Binary
      run: |
        make compress
        shasum -a 256 -t .build/mimiq.tar.gz | awk '{ print $1 }' > ~/mimiq_shasum
        awk '/version/{print $NF}' Sources/mimiq/Version.swift | sed -e 's/^"//' -e 's/"$//' > ~/mimiq_version
    - name: Upload Tar binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: .build/mimiq.tar.gz
        asset_name: mimiq.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
    - name: Upload Zip binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: .build/mimiq.zip
        asset_name: mimiq.zip
        tag: ${{ github.ref }}
        overwrite: true
    - name: Checkout to Homebrew core Repository
      uses: actions/checkout@v2
      with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
          repository: wendyliga/homebrew-core
          ref: refs/heads/master
    - name: Update mimiq Formula
      run: |
        mimiq_shasum=`awk '{ print $1 }' ~/mimiq_shasum`
        mimiq_version=`awk '{ print $1 }' ~/mimiq_version`
        mimiq_binary_url="https://github.com/wendyliga/mimiq/releases/download/"${mimiq_version}"/mimiq.tar.gz"
        sed "4s|.*|    url \"$mimiq_binary_url\"|" Formula/mimiq.rb > Formula/mimiq_temp.rb
        mv Formula/mimiq_temp.rb Formula/mimiq.rb
        sed "5s|.*|    sha256 \"$mimiq_shasum\"|" Formula/mimiq.rb > Formula/mimiq_temp.rb
        mv Formula/mimiq_temp.rb Formula/mimiq.rb
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
          committer: Wendy's Github Bot <github-bot@wendyliga.com>
          author: Wendy's Github Bot <github-bot@wendyliga.com>
          commit-message: 'update mimiq formula'
          title: 'Update mimiq formula'
          branch: mimiq
          branch-suffix: timestamp
          reviewers: wendyliga
          body: Automated changes created on [mimiq release](https://github.com/wendyliga/mimiq/releases)
    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"