
name: Release

on:
  push:
    tags:
      - '*'

jobs:
  upload_binary:
    name: Upload Binary
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compress Binary
      run: make compress
    - name: Upload Tar binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: .build/mimiq.tar.gz
        asset_name: mimiq.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
    - name: Upload Zip binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: .build/mimiq.zip
        asset_name: mimiq.zip
        tag: ${{ github.ref }}
        overwrite: true
  update_homebrew_formula:
    name: Update Homebrew Formula
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get Info
      run: |
        make compress
        shasum -a 256 -t .build/mimiq.tar.gz | awk '{ print $1 }' > ~/mimiq_shasum
        awk '/version/{print $NF}' Sources/mimiq/Version.swift | sed -e 's/^"//' -e 's/"$//' > ~/mimiq_version
    - name: Checkout to Homebrew core Repository
      uses: actions/checkout@v2
      with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
          repository: wendyliga/homebrew-core
          ref: refs/heads/master
    - name: Update mimiq Formula
      run: |
        mimiq_shasum=`awk '{ print $1 }' ~/mimiq_shasum`
        mimiq_version=${awk '{ print $1 }' ~/mimiq_version}
        mimiq_binary_url="https://github.com/wendyliga/mimiq/releases/download/"${mimiq_version}"/mimiq.tar.gz"
        sed "4s|.*|    url \"$mimiq_binary_url\"|" Formula/mimiq.rb > Formula/mimiq_temp.rb
        sed "5s|.*|    sha256 \"$mimiq_shasum\"|" Formula/mimiq.rb > Formula/mimiq_temp.rb
        mv Formula/mimiq_temp.rb Formula/mimiq.rb
    - name: Commit Changes
      uses: EndBug/add-and-commit@v4
      with:
          author_name: Wendy's Github Bot
          author_email: github-bot@wendyliga.com
          message: 'update mimiq formula'
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}

      