
name: Unit Test

on:
  push:
    branches: 
      - main
  pull_request:
    branches: [main]
    types: [synchronize, opened, reopened, ready_for_review]
      
jobs:
  macos_build_release:
    name: MacOS Build Release
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Release
      run: make build
  macos_test:
    name: MacOS Unit Test
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: make test
